# ============================================
# CONFIG WPA2 + PMF obligatoire — hostapd_wpa2_pmf2.conf
# PROTÉGÉ : deauth ignoré si client supporte PMF
# ieee80211w=2 → tous les clients doivent supporter PMF
# NOTE : driver brcmfmac du Pi ne supporte pas ieee80211w=2
#        → utiliser un AP Cisco/Ubiquiti/OpenWRT en prod
# ============================================
interface=wlan0
driver=nl80211
ssid=Lab-WPA2-PMF2
hw_mode=g
channel=6
ieee80211n=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=password123
ieee80211w=2
