# ============================================
# CONFIG WPA3-SAE — hostapd_wpa3.conf
# PROTÉGÉ : Dragonfly handshake + PMF obligatoire
# + Forward Secrecy + résistance aux attaques dico
# NOTE : driver brcmfmac du Pi ne supporte pas SAE
#        → démo théorique, AP réel requis en production
# ============================================
interface=wlan0
driver=nl80211
ssid=Lab-WPA3-Network
hw_mode=g
channel=6
ieee80211n=1
auth_algs=1
wpa=2
wpa_key_mgmt=SAE
rsn_pairwise=CCMP
sae_password=password123
ieee80211w=2
sae_anti_clogging_threshold=5
