# ============================================
# CONFIG WPA2 + PMF optionnel — hostapd_wpa2_pmf1.conf
# PARTIELLEMENT PROTÉGÉ : PMF optionnel (ieee80211w=1)
# Les clients qui supportent PMF sont protégés,
# les autres restent vulnérables au deauth
# NOTE : driver brcmfmac (Pi intégré) limite le support
# ============================================
interface=wlan0
driver=nl80211
ssid=Lab-WPA2-PMF1
hw_mode=g
channel=6
ieee80211n=1
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=password123
ieee80211w=1
