# ============================================
# CONFIG WEP — hostapd_wep.conf
# VULNÉRABLE : crack aircrack-ng en ~3 min
# ============================================
interface=wlan0
driver=nl80211
ssid=Lab-WEP-Network
hw_mode=g
channel=6
auth_algs=1
wep_default_key=0
wep_key0=AABBCCDDEE
